In [180]:
import numpy as np

bank_data = np.array([
    [101, 12500, 720, 45, 5],
    [102, 8200, 680, 30, 3],
    [103, 15400, 750, 60, 7],
    [104, 6400, 620, 22, 2],
    [105, 9800, 690, 35, 4],
    [106, 20000, 810, 80, 10],
    [107, 7300, 650, 28, 3],
    [108, 11200, 705, 40, 6],
    [109, 5400, 600, 18, 1],
    [110, 16800, 770, 65, 8]
])

print(bank_data)

[[  101 12500   720    45     5]
 [  102  8200   680    30     3]
 [  103 15400   750    60     7]
 [  104  6400   620    22     2]
 [  105  9800   690    35     4]
 [  106 20000   810    80    10]
 [  107  7300   650    28     3]
 [  108 11200   705    40     6]
 [  109  5400   600    18     1]
 [  110 16800   770    65     8]]


In [181]:
# Q1.1: Create a 4x4 identity matrix using np.eye()
identity_matrix=np.eye(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [182]:
# Q1.2: Create an array of 8 zeros using np.zeros()
zero_8=np.zeros(9)
zero_8


array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [183]:
# Q1.3: Create an array of 6 ones using np.ones()
ones_6=np.ones(6)
ones_6

array([1., 1., 1., 1., 1., 1.])

In [184]:
# Q1.4: Create an array with values from 0 to 15 using np.arange()
value_0_to_100=np.arange(0,16)
value_0_to_100


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [185]:

# Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()
even_space_8=np.linspace(1,100,8)
even_space_8

array([  1.        ,  15.14285714,  29.28571429,  43.42857143,
        57.57142857,  71.71428571,  85.85714286, 100.        ])

In [186]:

# Q2.1: What is the shape of the banking_data array?
bank_shape=bank_data.shape
bank_shape

(10, 5)

In [187]:
# Q2.2: What is the data type of the banking_data array?
bank_dtype=bank_data.dtype
bank_dtype


dtype('int64')

In [188]:
# Q2.3: What is the size (total number of elements) of the banking_data array?
bank_size=bank_data.size
bank_size


50

In [189]:
# Q2.4: What is the number of dimensions of the banking_data array?
bank_dim=bank_data.ndim
bank_dim


2

In [190]:
# Q2.5: What is the memory size of the banking_data array in bytes?
bank_byte=(bank_data.nbytes)
bank_byte


400

In [191]:
# Q3.1: Extract the first row of banking_data
first_row=bank_data[0]
first_row


array([  101, 12500,   720,    45,     5])

In [192]:
# Q3.2: Extract the last row of banking_data
last_row=bank_data[-1]
last_row


array([  110, 16800,   770,    65,     8])

In [193]:
# Q3.3: Extract the Account_Balance column (column index 1)
account_balance_column=bank_data[:,1]
account_balance_column


array([12500,  8200, 15400,  6400,  9800, 20000,  7300, 11200,  5400,
       16800])

In [194]:
# Q3.4: Extract the first 4 rows and first 3 columns
extract_4_3=bank_data[:4, :3]
extract_4_3


array([[  101, 12500,   720],
       [  102,  8200,   680],
       [  103, 15400,   750],
       [  104,  6400,   620]])

In [195]:
# Q3.5: Extract rows 3 to 7 (inclusive)
rows_3_7=bank_data[2:7]
rows_3_7


array([[  103, 15400,   750,    60,     7],
       [  104,  6400,   620,    22,     2],
       [  105,  9800,   690,    35,     4],
       [  106, 20000,   810,    80,    10],
       [  107,  7300,   650,    28,     3]])

In [196]:
# Q4.1: Calculate the sum of all account balances
cal_sum=np.sum(bank_data[:,1])
cal_sum


np.int64(113000)

In [197]:
# Q4.2: Calculate the mean account balance
cal_mean=np.mean(bank_data[:,1])
cal_mean


np.float64(11300.0)

In [198]:
# Q4.3: Calculate the standard deviation of account balances
cal_stddiv=np.std(bank_data[:,1])
cal_stddiv


np.float64(4592.167244341173)

In [199]:
# Q4.4: Calculate the variance of account balances
cal_var=np.var(bank_data[:,1])
print(cal_var)


21088000.0


In [200]:
# Q4.5: Calculate the median account balance
cal_median=np.median(bank_data[:, 1])
cal_median

np.float64(10500.0)

In [201]:
cal_min=np.min(bank_data[:,1])
cal_max=np.max(bank_data[:,1])
print(cal_min)
print(cal_max)

5400
20000


In [202]:
# Q5.2: Find the minimum and maximum credit scores
credit_min=np.min(bank_data[:,2])
credit_max=np.max(bank_data[:,2])
print(credit_min)
print(credit_max)


600
810


In [203]:
# Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
cal_percentile=np.percentile(bank_data[:,1],[25,50,75])
print(f"25th percentile: ${cal_percentile[0]:.2f}")
print(f"50th percentile: ${cal_percentile[1]:.2f}")
print(f"75th percentile: ${cal_percentile[2]:.2f}")


25th percentile: $7525.00
50th percentile: $10500.00
75th percentile: $14675.00


In [204]:
# Q5.4: Calculate the correlation between account balance and credit score
cal_correlation=np.corrcoef(bank_data[:,1], bank_data[:, 2])[0,1]
cal_correlation


np.float64(0.9825879667764666)

In [205]:
# Q5.5: Calculate the covariance between account balance and credit score
cal_covariance=np.cov(bank_data[:,1], bank_data[:,2])[0,1]
cal_covariance


np.float64(314388.8888888889)

In [206]:
# Q6.1: Reshape the banking_data to 5 rows × 10 columns
reshaped_size=bank_data.reshape(5,10)
reshaped_size

array([[  101, 12500,   720,    45,     5,   102,  8200,   680,    30,
            3],
       [  103, 15400,   750,    60,     7,   104,  6400,   620,    22,
            2],
       [  105,  9800,   690,    35,     4,   106, 20000,   810,    80,
           10],
       [  107,  7300,   650,    28,     3,   108, 11200,   705,    40,
            6],
       [  109,  5400,   600,    18,     1,   110, 16800,   770,    65,
            8]])

In [207]:
# Q6.2: Flatten the banking_data to a 1D array
bank_array=bank_data.flatten()
bank_array


array([  101, 12500,   720,    45,     5,   102,  8200,   680,    30,
           3,   103, 15400,   750,    60,     7,   104,  6400,   620,
          22,     2,   105,  9800,   690,    35,     4,   106, 20000,
         810,    80,    10,   107,  7300,   650,    28,     3,   108,
       11200,   705,    40,     6,   109,  5400,   600,    18,     1,
         110, 16800,   770,    65,     8])

In [208]:
bank_transpose=bank_data.T
bank_transpose

array([[  101,   102,   103,   104,   105,   106,   107,   108,   109,
          110],
       [12500,  8200, 15400,  6400,  9800, 20000,  7300, 11200,  5400,
        16800],
       [  720,   680,   750,   620,   690,   810,   650,   705,   600,
          770],
       [   45,    30,    60,    22,    35,    80,    28,    40,    18,
           65],
       [    5,     3,     7,     2,     4,    10,     3,     6,     1,
            8]])

In [209]:
# Q6.4: Split the banking_data into 2 equal parts vertically
split_vertical=np.vsplit(bank_data,2)
split_vertical


[array([[  101, 12500,   720,    45,     5],
        [  102,  8200,   680,    30,     3],
        [  103, 15400,   750,    60,     7],
        [  104,  6400,   620,    22,     2],
        [  105,  9800,   690,    35,     4]]),
 array([[  106, 20000,   810,    80,    10],
        [  107,  7300,   650,    28,     3],
        [  108, 11200,   705,    40,     6],
        [  109,  5400,   600,    18,     1],
        [  110, 16800,   770,    65,     8]])]

In [210]:
# Q6.5: Split the banking_data into 2 equal parts horizontally
split_hori=np.hsplit(bank_data,[3])
split_hori


[array([[  101, 12500,   720],
        [  102,  8200,   680],
        [  103, 15400,   750],
        [  104,  6400,   620],
        [  105,  9800,   690],
        [  106, 20000,   810],
        [  107,  7300,   650],
        [  108, 11200,   705],
        [  109,  5400,   600],
        [  110, 16800,   770]]),
 array([[45,  5],
        [30,  3],
        [60,  7],
        [22,  2],
        [35,  4],
        [80, 10],
        [28,  3],
        [40,  6],
        [18,  1],
        [65,  8]])]

In [211]:
# Q7.1: Find customers with account balance greater than $100,000

expensive_product=bank_data[bank_data[:,1]>100000]
expensive_product

array([], shape=(0, 5), dtype=int64)

In [212]:
# Q7.2: Find customers with credit score greater than 800
credit_score_greater=bank_data[bank_data[:,2]>800]
credit_score_greater


array([[  106, 20000,   810,    80,    10]])

In [213]:
# Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750
cus_tran_cnt=bank_data[(bank_data[:,3]>50)&(bank_data[:,2]<750)]
cus_tran_cnt


array([], shape=(0, 5), dtype=int64)

In [214]:
# Q7.4: Count how many customers have account balance between $10,000 and $100,000
cust_act_balance=np.sum((bank_data[:,1]>=10000)&(bank_data[:,1]<=100000))
cust_act_balance


np.int64(5)

In [215]:
# Q7.5: Find the index of the customer with the highest credit score
highest_index=np.argmax(bank_data[:,2])
print(highest_index)                     


5


In [216]:
# Q8.1: Sort the banking_data by account balance (ascending)
sort_by_price=bank_data[bank_data[:,1].argsort()]
sort_by_price

array([[  109,  5400,   600,    18,     1],
       [  104,  6400,   620,    22,     2],
       [  107,  7300,   650,    28,     3],
       [  102,  8200,   680,    30,     3],
       [  105,  9800,   690,    35,     4],
       [  108, 11200,   705,    40,     6],
       [  101, 12500,   720,    45,     5],
       [  103, 15400,   750,    60,     7],
       [  110, 16800,   770,    65,     8],
       [  106, 20000,   810,    80,    10]])

In [217]:
# Q8.2: Sort the banking_data by credit score (descending)
sort_by_score=bank_data[(-bank_data[:,2]).argsort()]
sort_by_score


array([[  106, 20000,   810,    80,    10],
       [  110, 16800,   770,    65,     8],
       [  103, 15400,   750,    60,     7],
       [  101, 12500,   720,    45,     5],
       [  108, 11200,   705,    40,     6],
       [  105,  9800,   690,    35,     4],
       [  102,  8200,   680,    30,     3],
       [  107,  7300,   650,    28,     3],
       [  104,  6400,   620,    22,     2],
       [  109,  5400,   600,    18,     1]])

In [218]:
# Q8.3: Find the indices that would sort the array by years active
rating_sort_indices=np.argsort(bank_data[:,2])
rating_sort_indices


array([8, 3, 6, 1, 4, 7, 0, 2, 9, 5])

In [219]:
# Q8.4: Find the customer with the second highest account balance
second_highest_price=np.argsort(bank_data[:,1])[1]
second_highest_price


np.int64(3)

In [220]:
# Q8.5: Find the customer with the lowest transaction count
lowest_index=bank_data[:,3].argmin()
lowest_index


np.int64(8)

In [221]:
# Q9.1: Calculate the absolute values of all elements
absolute_values=np.abs(bank_data)
absolute_values


array([[  101, 12500,   720,    45,     5],
       [  102,  8200,   680,    30,     3],
       [  103, 15400,   750,    60,     7],
       [  104,  6400,   620,    22,     2],
       [  105,  9800,   690,    35,     4],
       [  106, 20000,   810,    80,    10],
       [  107,  7300,   650,    28,     3],
       [  108, 11200,   705,    40,     6],
       [  109,  5400,   600,    18,     1],
       [  110, 16800,   770,    65,     8]])

In [222]:
# Q9.2: Calculate the square root of all account balances
cal_sqrt=np.sqrt(bank_data[:,1])
cal_sqrt


array([111.80339887,  90.55385138, 124.09673646,  80.        ,
        98.99494937, 141.42135624,  85.44003745, 105.83005244,
        73.48469228, 129.61481397])

In [223]:
# Q9.3: Calculate the square of all credit scores
cal_square=np.square(bank_data[:,2])
cal_square


array([518400, 462400, 562500, 384400, 476100, 656100, 422500, 497025,
       360000, 592900])

In [224]:
# Q9.4: Calculate the exponential of all transaction counts
cal_exponent=np.exp(bank_data[:,3])
cal_exponent


array([3.49342711e+19, 1.06864746e+13, 1.14200739e+26, 3.58491285e+09,
       1.58601345e+15, 5.54062238e+34, 1.44625706e+12, 2.35385267e+17,
       6.56599691e+07, 1.69488924e+28])

In [225]:
# Q9.5: Calculate the natural logarithm of all account balances
cal_log=np.log(bank_data[:,1])
cal_log


array([9.43348392, 9.01188943, 9.64212279, 8.76405327, 9.19013766,
       9.90348755, 8.89562963, 9.32366906, 8.59415423, 9.72913417])

In [226]:
# Q10.1: Calculate the cumulative sum of account balances
cal_cumsum=np.cumsum(bank_data[:,1])
cal_cumsum


array([ 12500,  20700,  36100,  42500,  52300,  72300,  79600,  90800,
        96200, 113000])

In [227]:
# Q10.2: Calculate the cumulative product of transaction counts
cal_cumprod=np.cumprod(bank_data[:,3])
cal_cumprod


array([              45,             1350,            81000,
                1782000,         62370000,       4989600000,
           139708800000,    5588352000000,  100590336000000,
       6538371840000000])

In [228]:
# Q10.3: Calculate the difference between consecutive account balances
cal_diff=np.diff(bank_data[:,1])
cal_diff

array([ -4300,   7200,  -9000,   3400,  10200, -12700,   3900,  -5800,
        11400])

In [229]:
# Q10.4: Calculate the gradient of account balances
cal_gradient=np.gradient(bank_data[:,1])
cal_gradient



array([-4300.,  1450.,  -900., -2800.,  6800., -1250., -4400.,  -950.,
        2800., 11400.])

In [230]:
# Q10.5: Calculate the histogram of account balances with 5 bins
hist_prices,bin_edges=np.histogram(bank_data[:,1],bins=5)
print(hist_prices)
print(bin_edges)


[4 2 1 2 1]
[ 5400.  8320. 11240. 14160. 17080. 20000.]


In [231]:
# Q11.1: Generate 6 random integers between 1 and 1000
random_ints=np.random.randint(1,1000,6)
random_ints

array([596, 107, 124, 570, 215, 738], dtype=int32)

In [232]:
random_float=np.random.random(6)
random_float

array([0.68482974, 0.4809319 , 0.39211752, 0.34317802, 0.72904971,
       0.43857224])

In [233]:
# Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)
normal_random=np.random.normal(700,100,6)
normal_random


array([685.66275259, 638.08090993, 623.05665285, 757.67460214,
       712.65259202, 569.85110255])

In [234]:
# Q11.4: Shuffle the banking_data rows randomly
shuffled_data=bank_data.copy()
np.random.shuffle(shuffled_data)
print(shuffled_data)

[[  108 11200   705    40     6]
 [  103 15400   750    60     7]
 [  110 16800   770    65     8]
 [  107  7300   650    28     3]
 [  104  6400   620    22     2]
 [  102  8200   680    30     3]
 [  101 12500   720    45     5]
 [  106 20000   810    80    10]
 [  109  5400   600    18     1]
 [  105  9800   690    35     4]]


In [235]:
# Q11.5: Set random seed to 123 and generate 4 random numbers
np.random.seed(123)
seeded_random=np.random.random(4)
print(seeded_random)


[0.69646919 0.28613933 0.22685145 0.55131477]


In [236]:
# Q12.1: Calculate the dot product of account balance and credit score columns
dot_product=np.dot(bank_data[:,1],bank_data[:,2])
dot_product


np.int64(81873000)

In [237]:
# Q12.2: Calculate the cross product of first two rows
cross_product=np.cross(bank_data[0,:3], bank_data[1,:3])
print(cross_product)


[2596000    4760 -446800]


In [238]:
# Q12.3: Calculate the norm (magnitude) of the account balance column
price_norm=np.linalg.norm(bank_data[:,1])
price_norm


np.float64(38571.751321401)

In [239]:
# Q12.4: Create a 3x3 matrix and calculate its determinant
matrix_2x2=np.array([[2,3],[1,4]])
determinant=np.linalg.det(matrix_2x2)
print(matrix_2x2)
print(determinant)


[[2 3]
 [1 4]]
5.000000000000001


In [240]:
# Q12.5: Calculate the inverse of the 3x3 matrix
inverse_matrix=np.linalg.inv(matrix_2x2)
print(inverse_matrix)


[[ 0.8 -0.6]
 [-0.2  0.4]]


In [241]:
# Q13.1: Convert all customer IDs to strings
customer_ids_Str=bank_data[:,0].astype(str)
customer_ids_Str

array(['101', '102', '103', '104', '105', '106', '107', '108', '109',
       '110'], dtype='<U21')

In [242]:
# Q13.2: Check if any customer ID contains '100'
contains_100=np.char.find(customer_ids_Str,'100')>=0
contains_100


array([False, False, False, False, False, False, False, False, False,
       False])

In [243]:
# Q13.3: Convert all customer IDs to uppercase (if they were strings)
customer_id_upper=np.char.upper(customer_ids_Str)
customer_id_upper


array(['101', '102', '103', '104', '105', '106', '107', '108', '109',
       '110'], dtype='<U21')

In [244]:
# Q13.4: Count the length of each customer ID string
id_lenghts=np.char.str_len(customer_ids_Str)
id_lenghts


array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [245]:
# Q13.5: Replace '100' with 'CUST' in customer IDs
replaced_ids=np.char.replace(customer_ids_Str,'100','prod')
replaced_ids


array(['101', '102', '103', '104', '105', '106', '107', '108', '109',
       '110'], dtype='<U3')

In [246]:
# Q13.5: Replace '100' with 'CUST' in customer IDs
years_to_months=bank_data[:,4]*12
years_to_months


array([ 60,  36,  84,  24,  48, 120,  36,  72,  12,  96])

In [247]:
# Q14.2: Calculate the average years active
avg_years_active=np.mean(bank_data[:,4])
avg_years_active


np.float64(4.9)

In [248]:
# Q14.3: Find customers who have been active for more than 5 years
active_customers=bank_data[bank_data[:,4]>5]
active_customers

array([[  103, 15400,   750,    60,     7],
       [  106, 20000,   810,    80,    10],
       [  108, 11200,   705,    40,     6],
       [  110, 16800,   770,    65,     8]])

In [249]:
# Q14.4: Calculate the total time all customers have been active (in years)
total_years_active=np.sum(bank_data[:,4])
total_years_active


np.int64(49)

In [250]:
# Q14.5: Find the customer with the shortest time active
shortest_index=bank_data[:,4].argmin()
shortest_index


np.int64(8)

In [251]:
# Q15.1: Apply a function to calculate 5% interest on all account balances
interest=bank_data[:,1]*0.05
interest

array([ 625.,  410.,  770.,  320.,  490., 1000.,  365.,  560.,  270.,
        840.])

In [252]:
# Q15.2: Use np.where to categorize customers by balance ranges
categorize=np.where(bank_data[:,1]<8000, "Low",
                    np.where(bank_data[:,1]<=15000,"Median","HIgh"))
categorize


array(['Median', 'Median', 'HIgh', 'Low', 'Median', 'HIgh', 'Low',
       'Median', 'Low', 'HIgh'], dtype='<U6')

In [256]:
# Q16.1: Concatenate two arrays horizontally using np.hstack()
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
hstacked=np.hstack([arr1,arr2])
print(hstacked)


[1 2 3 4 5 6]


In [257]:
# Q16.2: Concatenate two arrays vertically using np.vstack()
vstacked=np.vstack([arr1,arr2])
vstacked


array([[1, 2, 3],
       [4, 5, 6]])

In [259]:
# Q16.3: Concatenate arrays along a specific axis using np.concatenate()
concat_array=np.concatenate([arr1,arr2])
concat_array


array([1, 2, 3, 4, 5, 6])

In [260]:
# Q16.4: Stack arrays depth-wise using np.dstack()
dept_array=np.dstack([arr1,arr2])
dept_array


array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [265]:
# Q16.5: Create a column stack using np.column_stack()
column_array=np.column_stack((arr1,arr2))
column_array


array([[1, 4],
       [2, 5],
       [3, 6]])

In [271]:
# Q17.1: Split an array into 3 equal parts using np.split()
parts=np.array([1,2,3,4,5,6,7,8,9])
split_parts=np.split(parts,3)
split_parts


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [275]:
# Q17.2: Split an array at specific indices using np.split()
split_arr=np.split(bank_data,[2,6])
split_arr


[array([[  101, 12500,   720,    45,     5],
        [  102,  8200,   680,    30,     3]]),
 array([[  103, 15400,   750,    60,     7],
        [  104,  6400,   620,    22,     2],
        [  105,  9800,   690,    35,     4],
        [  106, 20000,   810,    80,    10]]),
 array([[  107,  7300,   650,    28,     3],
        [  108, 11200,   705,    40,     6],
        [  109,  5400,   600,    18,     1],
        [  110, 16800,   770,    65,     8]])]

In [319]:
# Q17.3: Split an array horizontally using np.hsplit()
split_horizontal=np.hsplit(bank_data,5)
split_horizontal


[array([[101],
        [102],
        [103],
        [104],
        [105],
        [106],
        [107],
        [108],
        [109],
        [110]]),
 array([[12500],
        [ 8200],
        [15400],
        [ 6400],
        [ 9800],
        [20000],
        [ 7300],
        [11200],
        [ 5400],
        [16800]]),
 array([[720],
        [680],
        [750],
        [620],
        [690],
        [810],
        [650],
        [705],
        [600],
        [770]]),
 array([[45],
        [30],
        [60],
        [22],
        [35],
        [80],
        [28],
        [40],
        [18],
        [65]]),
 array([[ 5],
        [ 3],
        [ 7],
        [ 2],
        [ 4],
        [10],
        [ 3],
        [ 6],
        [ 1],
        [ 8]])]

In [282]:
# Q17.4: Split an array vertically using np.vsplit()
split_vertical=np.vsplit(bank_data,2)
split_vertical


[array([[  101, 12500,   720,    45,     5],
        [  102,  8200,   680,    30,     3],
        [  103, 15400,   750,    60,     7],
        [  104,  6400,   620,    22,     2],
        [  105,  9800,   690,    35,     4]]),
 array([[  106, 20000,   810,    80,    10],
        [  107,  7300,   650,    28,     3],
        [  108, 11200,   705,    40,     6],
        [  109,  5400,   600,    18,     1],
        [  110, 16800,   770,    65,     8]])]

In [286]:
# Q17.5: Split an array into equal chunks using np.array_split()
equal_array=np.array_split(bank_data,4)
equal_array


[array([[  101, 12500,   720,    45,     5],
        [  102,  8200,   680,    30,     3],
        [  103, 15400,   750,    60,     7]]),
 array([[  104,  6400,   620,    22,     2],
        [  105,  9800,   690,    35,     4],
        [  106, 20000,   810,    80,    10]]),
 array([[  107,  7300,   650,    28,     3],
        [  108, 11200,   705,    40,     6]]),
 array([[  109,  5400,   600,    18,     1],
        [  110, 16800,   770,    65,     8]])]

In [291]:
# Q18.1: Repeat each element of an array 3 times using np.repeat()
array_rep=np.repeat(bank_data,3)
array_rep


array([  101,   101,   101, 12500, 12500, 12500,   720,   720,   720,
          45,    45,    45,     5,     5,     5,   102,   102,   102,
        8200,  8200,  8200,   680,   680,   680,    30,    30,    30,
           3,     3,     3,   103,   103,   103, 15400, 15400, 15400,
         750,   750,   750,    60,    60,    60,     7,     7,     7,
         104,   104,   104,  6400,  6400,  6400,   620,   620,   620,
          22,    22,    22,     2,     2,     2,   105,   105,   105,
        9800,  9800,  9800,   690,   690,   690,    35,    35,    35,
           4,     4,     4,   106,   106,   106, 20000, 20000, 20000,
         810,   810,   810,    80,    80,    80,    10,    10,    10,
         107,   107,   107,  7300,  7300,  7300,   650,   650,   650,
          28,    28,    28,     3,     3,     3,   108,   108,   108,
       11200, 11200, 11200,   705,   705,   705,    40,    40,    40,
           6,     6,     6,   109,   109,   109,  5400,  5400,  5400,
         600,   600,

In [293]:
# Q18.2: Repeat an entire array 2 times using np.tile()
array_title=np.tile(bank_data,2)
array_title


array([[  101, 12500,   720,    45,     5,   101, 12500,   720,    45,
            5],
       [  102,  8200,   680,    30,     3,   102,  8200,   680,    30,
            3],
       [  103, 15400,   750,    60,     7,   103, 15400,   750,    60,
            7],
       [  104,  6400,   620,    22,     2,   104,  6400,   620,    22,
            2],
       [  105,  9800,   690,    35,     4,   105,  9800,   690,    35,
            4],
       [  106, 20000,   810,    80,    10,   106, 20000,   810,    80,
           10],
       [  107,  7300,   650,    28,     3,   107,  7300,   650,    28,
            3],
       [  108, 11200,   705,    40,     6,   108, 11200,   705,    40,
            6],
       [  109,  5400,   600,    18,     1,   109,  5400,   600,    18,
            1],
       [  110, 16800,   770,    65,     8,   110, 16800,   770,    65,
            8]])

In [294]:
# Q18.3: Repeat a 2D array using np.tile()

arr=np.array([[1,2],[3,4]])
tiled=np.tile(arr,(2,3))
print(tiled)

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [295]:
tile_array=np.tile(bank_data,3)
tile_array

array([[  101, 12500,   720,    45,     5,   101, 12500,   720,    45,
            5,   101, 12500,   720,    45,     5],
       [  102,  8200,   680,    30,     3,   102,  8200,   680,    30,
            3,   102,  8200,   680,    30,     3],
       [  103, 15400,   750,    60,     7,   103, 15400,   750,    60,
            7,   103, 15400,   750,    60,     7],
       [  104,  6400,   620,    22,     2,   104,  6400,   620,    22,
            2,   104,  6400,   620,    22,     2],
       [  105,  9800,   690,    35,     4,   105,  9800,   690,    35,
            4,   105,  9800,   690,    35,     4],
       [  106, 20000,   810,    80,    10,   106, 20000,   810,    80,
           10,   106, 20000,   810,    80,    10],
       [  107,  7300,   650,    28,     3,   107,  7300,   650,    28,
            3,   107,  7300,   650,    28,     3],
       [  108, 11200,   705,    40,     6,   108, 11200,   705,    40,
            6,   108, 11200,   705,    40,     6],
       [  109,  5400,   

In [296]:
# Q18.4: Create a pattern using np.tile()
pattern=np.tile(bank_data,2)
pattern


array([[  101, 12500,   720,    45,     5,   101, 12500,   720,    45,
            5],
       [  102,  8200,   680,    30,     3,   102,  8200,   680,    30,
            3],
       [  103, 15400,   750,    60,     7,   103, 15400,   750,    60,
            7],
       [  104,  6400,   620,    22,     2,   104,  6400,   620,    22,
            2],
       [  105,  9800,   690,    35,     4,   105,  9800,   690,    35,
            4],
       [  106, 20000,   810,    80,    10,   106, 20000,   810,    80,
           10],
       [  107,  7300,   650,    28,     3,   107,  7300,   650,    28,
            3],
       [  108, 11200,   705,    40,     6,   108, 11200,   705,    40,
            6],
       [  109,  5400,   600,    18,     1,   109,  5400,   600,    18,
            1],
       [  110, 16800,   770,    65,     8,   110, 16800,   770,    65,
            8]])

In [297]:
# Q18.5: Repeat elements with different counts using np.repeat()

repeated=np.repeat(bank_data,1)
repeated

array([  101, 12500,   720,    45,     5,   102,  8200,   680,    30,
           3,   103, 15400,   750,    60,     7,   104,  6400,   620,
          22,     2,   105,  9800,   690,    35,     4,   106, 20000,
         810,    80,    10,   107,  7300,   650,    28,     3,   108,
       11200,   705,    40,     6,   109,  5400,   600,    18,     1,
         110, 16800,   770,    65,     8])

In [301]:
# Q19.1: Compare two arrays for equality using np.array_equal()
equality=np.array_equal(arr1,arr2)
equality


False

In [303]:
# Q19.2: Check if arrays are close using np.allclose()
array_close=np.allclose(arr1,arr2)
array_close


False

In [304]:
# Q19.3: Apply logical AND operation between arrays
array_And=np.logical_and(arr1,arr2)
array_And


array([ True,  True,  True])

In [306]:
# Q19.4: Apply logical OR operation between arrays
array_or=np.logical_or(arr1,arr2)
array_or


array([ True,  True,  True])

In [307]:
# Q19.5: Apply logical NOT operation to an array
array_not=np.logical_not(arr1,arr2)
array_not


array([0, 0, 0])

In [308]:
# Q20.1: Find unique elements in an array using np.unique()
array_unique=np.unique(bank_data)
array_unique


array([    1,     2,     3,     4,     5,     6,     7,     8,    10,
          18,    22,    28,    30,    35,    40,    45,    60,    65,
          80,   101,   102,   103,   104,   105,   106,   107,   108,
         109,   110,   600,   620,   650,   680,   690,   705,   720,
         750,   770,   810,  5400,  6400,  7300,  8200,  9800, 11200,
       12500, 15400, 16800, 20000])

In [312]:
# Q20.2: Find the intersection of two arrays using np.intersect1d()
array_intersect=np.intersect1d(arr1,arr2)
array_intersect


array([], dtype=int64)

In [315]:
# Q20.3: Find the union of two arrays using np.union1d()
array_union=np.union1d(arr1,arr2)
array_union


array([0, 1, 2, 3])

In [316]:
# Q20.4: Find elements in first array but not in second using np.setdiff1d()
array_diff=np.setdiff1d(arr1,arr2)
array_diff


array([1, 2, 3])

In [318]:
# Q20.5: Find the symmetric difference between two arrays using np.setxor1d()
array_sym=np.setxor1d(arr1,arr2)
array_sym


array([0, 1, 2, 3])