In [1]:
import numpy as np

In [2]:
data=np.random.randint(0,100,10)

In [3]:
data

array([54, 25, 74, 18, 12, 81, 59, 43, 90, 30])

In [4]:
data.min()

np.int64(12)

In [5]:
data.max()

np.int64(90)

In [7]:
range=data.max()-data.min()
range

np.int64(78)

In [9]:
data.mean()

np.float64(48.6)

In [11]:
np.median(data)

np.float64(48.5)

In [12]:
np.std(data)

np.float64(25.99307600111999)

In [13]:
np.var(data)

np.float64(675.64)

In [15]:
np.quantile(data,0.25)

np.float64(26.25)

In [18]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])
print(np.quantile(data, 0.5))

30.0


In [19]:
np.quantile(data,0.50),np.median(data)

(np.float64(30.0), np.float64(30.0))

In [20]:
np.quantile(data,0.75)

np.float64(40.0)

In [22]:
iqr=np.quantile(data,0.75)-np.quantile(data,0.25)
iqr

np.float64(20.0)

In [23]:
import numpy as np
np.random.seed(121)
data=np.random.randint(0,100,10)
data

array([66, 85,  8, 95, 65, 52, 83, 96, 46, 34])

In [24]:
data=np.random.randint(0,10,(3,10))

In [25]:
data

array([[4, 6, 3, 9, 4, 9, 8, 6, 7, 5],
       [9, 9, 7, 3, 4, 8, 3, 4, 3, 4],
       [2, 7, 7, 6, 4, 4, 9, 8, 0, 7]])

In [26]:
np.corrcoef(data)

array([[ 1.        , -0.29464184,  0.04777959],
       [-0.29464184,  1.        , -0.13225824],
       [ 0.04777959, -0.13225824,  1.        ]])

In [27]:
data.T

array([[4, 9, 2],
       [6, 9, 7],
       [3, 7, 7],
       [9, 3, 6],
       [4, 4, 4],
       [9, 8, 4],
       [8, 3, 9],
       [6, 4, 8],
       [7, 3, 0],
       [5, 4, 7]])

In [28]:
import numpy as np
data=np.array([10,20,np.nan,40,50,np.nan,70])
print("Original data:", data)


Original data: [10. 20. nan 40. 50. nan 70.]


In [29]:
print("Null positions:", np.isnan(data))

Null positions: [False False  True False False  True False]


In [30]:
np.isnan(data).sum()

np.int64(2)

In [31]:
clean_data=data[~np.isnan(data)]
print("After removing nulls:", clean_data)

After removing nulls: [10. 20. 40. 50. 70.]


In [33]:
replace_zero=np.nan_to_num(data,nan=20)
print("Replace nan with 0:", replace_zero)

Replace nan with 0: [10. 20. 20. 40. 50. 20. 70.]


In [34]:
np.nanmean(data)

np.float64(38.0)

In [35]:
data.mean()

np.float64(nan)

In [36]:
np.nanmedian(data)

np.float64(40.0)

In [37]:
np.where(np.isnan(data),np.nanmedian(data),data)

array([10., 20., 40., 40., 50., 40., 70.])

In [38]:
import numpy as np
data=np.array([10,20,np.nan,40,50,np.nan,70])
print("Original data:", data)
print("Null Positions:", np.isnan(data))
print("Total Null Values:", np.isnan(data).sum())
lean_data = data[~np.isnan(data)]
print("After Removing Nulls:", clean_data)




Original data: [10. 20. nan 40. 50. nan 70.]
Null Positions: [False False  True False False  True False]
Total Null Values: 2
After Removing Nulls: [10. 20. 40. 50. 70.]


In [39]:
print(data)

[10. 20. nan 40. 50. nan 70.]


In [40]:
print(np.isnan(data))

[False False  True False False  True False]


In [42]:
print(np.isnan(data).sum())

2


In [44]:
clean_data=data[~np.isnan(data)]
clean_data

array([10., 20., 40., 50., 70.])

In [46]:
replace_zero=np.nan_to_num(data,nan=0)
replace_zero

array([10., 20.,  0., 40., 50.,  0., 70.])