In [1]:
import numpy as np

In [2]:
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])

In [3]:
print("Array A:", a)
print("Array B:", b)

Array A: [10 20 30 40]
Array B: [1 2 3 4]


In [4]:
print("\nAdditon (np.add):")
print(np.add(a, b))


Additon (np.add):
[11 22 33 44]


In [5]:
print("\nSubtraction (np.subtract):")
print(np.subtract(a,b))


Subtraction (np.subtract):
[ 9 18 27 36]


In [6]:
print("\nMultiplication (np.multiply)")
print(np.multiply(a,b))


Multiplication (np.multiply)
[ 10  40  90 160]


In [7]:
print("\nDivision (np.divide):")
print(np.divide(a, b))


Division (np.divide):
[10. 10. 10. 10.]


In [8]:
print("\nPower (np.power):")
print(np.power(a,b))



Power (np.power):
[     10     400   27000 2560000]


In [9]:
print("\nModulus (np.mod):")
print(np.mod(a,b))



Modulus (np.mod):
[0 0 0 0]


In [10]:
print("\nFloor Division (np.floor_divide):")
print(np.floor_divide(a,b))



Floor Division (np.floor_divide):
[10 10 10 10]


In [11]:
print("\nAbsolute  Difference(np.divide):")
print(np.abs(a-b))



Absolute  Difference(np.divide):
[ 9 18 27 36]


In [14]:
x=(1,2,3,4)
type(x)

tuple

In [15]:
x=[1,2,3,4]
type(x)

list

In [16]:
y=np.array(x)
type(y)

numpy.ndarray

In [17]:
type(x),type(y)

(list, numpy.ndarray)

In [18]:
y/2

array([0.5, 1. , 1.5, 2. ])

In [19]:
x=[1,2,2.7+4j,"data"]
x

[1, 2, (2.7+4j), 'data']

In [21]:
y=np.array(x)
y

array(['1', '2', '(2.7+4j)', 'data'], dtype='<U64')

In [22]:
data=np.random.randint(0,255,(3,3))

In [23]:
data

array([[143,  36,  57],
       [135, 164,   8],
       [ 19,  43, 112]])

In [24]:
np.random.rand(3,3)

array([[0.20699368, 0.02848971, 0.29175971],
       [0.33535824, 0.32993119, 0.33750662],
       [0.39201321, 0.69527683, 0.34022726]])

In [25]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [26]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [27]:
range(0,10)

range(0, 10)

In [28]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [29]:
np.arange(0,100,2)
np.linspace(0,10,4)
np.eye(3)
data.shape,data.size,data.ndim

((3, 3), 9, 2)

In [31]:
data=np.random.randint(0,10,(3,3))
data

array([[4, 0, 4],
       [9, 7, 8],
       [5, 0, 2]])

In [32]:
data.shape,data.size,data.ndim

((3, 3), 9, 2)

In [36]:
data=np.random.randint(0,10,(3,3))
data

array([[7, 3, 5],
       [4, 4, 3],
       [3, 1, 1]])

In [38]:
data.T

array([[7, 4, 3],
       [3, 4, 1],
       [5, 3, 1]])

In [39]:
import numpy as np
np.random.seed(121)
data=np.random.randint(0,100,(5,5))
data

array([[66, 85,  8, 95, 65],
       [52, 83, 96, 46, 34],
       [52, 60, 54,  3, 94],
       [52, 57, 75, 88, 39],
       [21, 41, 55, 83, 94]])

In [40]:
data[2:4,-3:-1]

array([[54,  3],
       [75, 88]])

In [41]:
data[4,0:2]

array([21, 41])

In [42]:
data[0:4,4]

array([65, 34, 94, 39])

In [44]:
data[0:2,0:2]

array([[66, 85],
       [52, 83]])

In [45]:
data[0,0]

np.int64(66)

In [48]:
data[-3:-1,0:2]

array([[52, 60],
       [52, 57]])

In [46]:
data

array([[66, 85,  8, 95, 65],
       [52, 83, 96, 46, 34],
       [52, 60, 54,  3, 94],
       [52, 57, 75, 88, 39],
       [21, 41, 55, 83, 94]])

In [49]:
data=np.random.randint(0,10,(3,3))
data

array([[8, 3, 4],
       [3, 4, 2],
       [7, 7, 6]])

In [50]:
data.sum(axis=1)

array([15,  9, 20])

In [51]:
data.sum(axis=0)

array([18, 14, 12])

In [52]:
data.min(axis=1)

array([3, 2, 6])

In [53]:
data.min(axis=0)

array([3, 3, 2])

In [54]:
data.max()

np.int64(8)

In [55]:
data.max(axis=1)

array([8, 4, 7])

In [56]:
data.mean(axis=0)

array([6.        , 4.66666667, 4.        ])

In [57]:
data.mean(axis=1)

array([5.        , 3.        , 6.66666667])

In [58]:
data.mean()

np.float64(4.888888888888889)

In [59]:
data.argmin(axis=1)

array([1, 2, 2])

In [60]:
data

array([[8, 3, 4],
       [3, 4, 2],
       [7, 7, 6]])

In [61]:
data.argmax(axis=0)

array([0, 2, 2])

In [62]:
x=np.random.randint(0,10,(2,5))
y=np.random.randint(0,10,(2,10))

In [63]:
x

array([[4, 4, 9, 8, 0],
       [7, 7, 1, 3, 2]])

In [64]:
y

array([[1, 4, 7, 0, 3, 7, 6, 1, 1, 9],
       [4, 3, 9, 2, 7, 5, 1, 6, 0, 8]])

In [66]:
from numpy.linalg import inv

In [67]:
inv(data)

array([[ 0.25 ,  0.25 , -0.25 ],
       [-0.1  ,  0.5  , -0.1  ],
       [-0.175, -0.875,  0.575]])

In [68]:
a=np.array([4,9,16,25])
b=np.array([1,2,3,4])

In [69]:
np.e

2.718281828459045

In [70]:
print(np.sqrt(a))
print(np.square(b))
print(np.power(b,a))
print(np.exp(b))
print(np.log(a))
print(np.log2(a))
print(np.log10(a))

[2. 3. 4. 5.]
[ 1  4  9 16]
[               1              512         43046721 1125899906842624]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[1.38629436 2.19722458 2.77258872 3.21887582]
[2.         3.169925   4.         4.64385619]
[0.60205999 0.95424251 1.20411998 1.39794001]


In [71]:
print(np.sqrt(a))


[2. 3. 4. 5.]


In [72]:
print(np.square(b))


[ 1  4  9 16]


In [73]:
print(np.power(b,3))


[ 1  8 27 64]


In [74]:
print(np.exp(b))


[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [75]:
print(np.log(a))


[1.38629436 2.19722458 2.77258872 3.21887582]


In [76]:
print(np.log2(a))


[2.         3.169925   4.         4.64385619]


In [77]:
print(np.log10(a))

[0.60205999 0.95424251 1.20411998 1.39794001]


In [78]:
np.log2(9)

np.float64(3.169925001442312)

In [79]:
a

array([ 4,  9, 16, 25])

In [80]:
x=a/2

In [81]:
x

array([ 2. ,  4.5,  8. , 12.5])

In [82]:
print(np.ceil(x))

[ 2.  5.  8. 13.]


In [83]:
print(np.floor(x))

[ 2.  4.  8. 12.]


In [86]:
b=np.array([1,2.3,3.5,4.7])

In [87]:
print(np.ceil(b))

[1. 3. 4. 5.]


In [88]:
print(np.floor(b))

[1. 2. 3. 4.]


In [89]:
print(np.round(b))

[1. 2. 4. 5.]


In [90]:
print(np.trunc(b))

[1. 2. 3. 4.]


In [91]:
print(np.sign([-10,20,0,10]))

[-1  1  0  1]


In [92]:
a

array([ 4,  9, 16, 25])

In [93]:
b

array([1. , 2.3, 3.5, 4.7])

In [94]:
np.maximum(a,b*10)

array([10., 23., 35., 47.])